#pragma once

#define LED_WIN_LOCK_PIN B10
#define LED_MAC_PIN B11

#define SPI_DRIVER SPIDQ
#define SPI_SCK_PIN B3
#define SPI_MOSI_PIN B5
#define SPI_MISO_PIN B4

#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN C12
#define WEAR_LEVELING_LOGICAL_SIZE (WEAR_LEVELING_BACKING_SIZE / 2)

#define WS2812_SPI_DRIVER SPIDM2
#define WS2812_SPI_DIVISOR 32